# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20c24b75f626444ea39f114d239a3d33d24606fa921cbbdf8b49ffb5db9b2bed9be556bd7b811a8ebcb6497247570c4013b3740dd40bc49eed7592d2b5468e19

test:
  secret_key_base: df740d243dc5e0c1c1727ddd49d34f3aa89cbefc7acfede213f7ca5fc44c343d5059f9bc638a3b8b62ca2579a34e83ca4ca57fc4e41f4e89198e961a544a331f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
